name: Check Typos

on:
  push:
    branches:
      - main
      - readme-setup
  pull_request:
    branches:
      - main

jobs:
  typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          sudo apt-get install -y languagetool

      - name: Check typos in README (French)
        run: languagetool -l fr README.md

      - name: Check typos in Markdown files (French)
        run: find . -type f -name "*.md" | xargs -I {} languagetool -l fr {}

      - name: Fail if any typos found
        if: ${{ always() }}
        run: |
          if languagetool -l fr README.md; then
            echo "French typos found in README"
            exit 1
          fi

          if find . -type f -name "*.md" | xargs -I {} languagetool -l fr {}; then
            echo "French typos found in Markdown files"
            exit 1
          fi
